Улучшить Filmorate - добавление в друзья и лайков фильмам
SmirnovSA1/java-filmorate pull request #6
Opened 2024-02-23 22:12 UTC by SmirnovSA1

В рамках ТЗ-10 требуется:

**Архитектура**
- Создать классы InMemoryFilmStorage и InMemoryUserStorage, имплементирующие новые интерфейсы, и перенесите туда всю логику хранения, обновления и поиска объектов.
- Добавить к InMemoryFilmStorage и InMemoryUserStorage аннотацию @Component, чтобы впоследствии пользоваться внедрением зависимостей и передавать хранилища сервисам.

**Новая логика**
- Создать UserService, который будет отвечать за такие операции с пользователями, как добавление в друзья, удаление из друзей, вывод списка общих друзей. Пока пользователям не надо одобрять заявки в друзья — добавляем сразу.
- Создать FilmService, который будет отвечать за операции с фильмами, — добавление и удаление лайка, вывод 10 наиболее популярных фильмов по количеству лайков. Пусть пока каждый пользователь может поставить лайк фильму только один раз.
- Добавить к ним аннотацию @Service.

**Зависимости**
- Переделать код в контроллерах, сервисах и хранилищах под использование внедрения зависимостей. 
- Внедрить зависимости через конструкторы классов.
- Обеспечить классам-сервисам доступ к классам-хранилищам. Сервисы должны зависеть от интерфейсов классов-хранилищ, а не их реализаций.
- Внедрить сервисы в соответствующие контроллеры.

**Полный REST**
- Добавить возможность получать каждый фильм и данные о пользователях по их уникальному идентификатору: GET .../users/{id}.
- Добавить методы, позволяющие пользователям добавлять друг друга в друзья, получать список общих друзей и лайкать фильмы. Проверить, что все они работают корректно.
        1. PUT /users/{id}/friends/{friendId} — добавление в друзья.
        2. DELETE /users/{id}/friends/{friendId} — удаление из друзей.
        3. GET /users/{id}/friends — возвращаем список пользователей, являющихся его друзьями.
        4. GET /users/{id}/friends/common/{otherId} — список друзей, общих с другим пользователем.
        5. PUT /films/{id}/like/{userId} — пользователь ставит лайк фильму.
        6. DELETE /films/{id}/like/{userId} — пользователь удаляет лайк.
        7. GET /films/popular?count={count} — возвращает список из первых count фильмов по количеству лайков. Если значение параметра count не задано, верните первые 10.
- Убедиться, что приложение возвращает корректные HTTP-коды.
        1. 400 — если ошибка валидации: ValidationException;
        2. 404 — для всех ситуаций, если искомый объект не найден;
        3. 500 — если возникло исключение.

2024-02-24 22:25 UTC, andrew-larkin requested changes
Привет! Очень хорошо реализовал новый функционал, все четко и чисто, молодец! небольшие правки по коду и тестам - их поправить и сможем двигаться дальше.

2024-02-24 22:25 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
чтобы не создавать конструктор в контроллере, можем повесить @RequiredArgsConstructor над классом и тогда все поля, помеченные final, будут добавлены в неявный конструктор и это приведет к внедрению зависимости

2024-02-24 22:25 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film film1;
можно в каждом тесте просто заново создавать объекты

2024-02-24 22:25 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void setUp() {
нагрузка большая. лучше как-ниубдь разделить это дело

2024-02-25 09:32 UTC, SmirnovSA1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Добавил аннотацию @RequiredArgsConstructor к классу FilmController

2024-02-25 09:32 UTC, SmirnovSA1 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private Film film1;
Создание необходимых объектов вынес в каждый тесте, чтобы не было большой нагрузки.

2024-02-25 09:32 UTC, SmirnovSA1 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void setUp() {
Создание необходимых объектов вынес в каждый тесте, чтобы не было большой нагрузки.

2024-03-02 21:22 UTC, merged